config/routes.rb
Rails.application.routes.draw do
  resources :artworks

  root 'welcome#index'

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    @artworks = Artwork.all
  end

  def edit
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artworks/edit.html.haml
.thumbnail
  Edit screen
  %p
    = link_to "Delete", "#", class: "btn btn-primary", role: "button"

app/views/artworks/index.html.haml
%h1 All Artworks
= link_to root_path do
  #logo.v-h-center

.artwork-thumbs
  - @artworks.each do |artwork|
    .thumbnail
      %h3= artwork.name
      %p
        - artwork.attributes.values_at('picture', 'description').each do |v|
          = v
          %br
      %p.text-center
        = link_to "Edit", edit_artwork_path(artwork), class: "btn btn-primary", role: "button"
        = link_to "Show", artwork, class: "btn btn-default", role: "button"

app/views/artworks/show.html.haml
.thumbnail
  Show screen

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title ArtistHome
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{class: ("front-page" if controller_name == "welcome")}
    = yield

app/views/welcome/index.html.haml
%h1 Welcome!
= link_to artworks_path do
  #custom-link.v-h-center all artworks